import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button, Container, List, ListItem, ListItemText, Typography } from '@mui/material'
import GridCenter from '@//CenterContents'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SSR Pagination</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{marginTop:'10px'}}>
        <Typography variant="h2" gutterBottom>SSR Pagination</Typography>
        <List dense >
          <ListItem >
            <ListItemText>Server Side Rendering</ListItemText>
          </ListItem>
          <ListItem>
            <ListItemText>Deabounce</ListItemText>
          </ListItem>
          <ListItem>
            <ListItemText>Persist Pagination</ListItemText>
          </ListItem>
        </List>        
        <GridCenter>
          <Button variant="outlined">
            <Link href="/pagination">Click Here</Link>
          </Button>
        </GridCenter>
      </Container>
    </div>
  )
}

export default Home
